---
- name: create mgr directory
  file:
    path: /var/lib/ceph/mgr/
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: create mgr directory
  file:
    path: /var/lib/ceph/mgr/{{ cluster }}-{{ ansible_hostname }}
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- include: copy_configs.yml
- include: start_docker_mgr.yml
